service: ${env:SERVICE_NAME}

frameworkVersion: "3"

provider:
  name: aws
  runtime: provided.al2

  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

  deploymentBucket:
    name: "sls-deployment-bucket-${env:SERVICE_NAME}-${env:STAGE}"
    serverSideEncryption: AES256

  logRetentionInDays: 1

  environment:
    INVOKED_FUNCTION_NAME: ${env:INVOKED_FUNCTION_NAME}
    SLACK_ACCESS_TOKEN: ${env:SLACK_ACCESS_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_VERIFICATION_TOKEN: ${env:SLACK_VERIFICATION_TOKEN}
    DEEPL_API_KEY: ${env:DEEPL_API_KEY}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource:
            - ${env:AWS_RESOURCE}

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization

custom:
  deploymentBucket:
    blockPublicAccess: true
  go:
    cmd: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true

package:
  individually: true
  exclude:
    - "./**"

plugins:
  - serverless-deployment-bucket
  - serverless-go-plugin

functions:
  eventReceiver:
    handler: event/receiver/main.go
    events:
      - httpApi:
          path: /event/receiver
          method: post
  eventAction:
    handler: event/action/main.go
